config/routes.rb
Rails.application.routes.draw do
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'home#index'

  # root "articles#index"

  get 'home' => 'home#index'

  get 'articles' => 'articles#index'

  get 'articles/new' => 'articles#new'
  post 'articles' => 'articles#create'

  get 'articles/:id' => 'articles#show'

  get 'articles/:id/edit' => 'articles#edit'
  put 'articles/:id' => 'articles#update'

  delete 'articles/:id' => 'articles#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :has_categories
    has_many :categories, through: :has_categories
    attr_accessor :category_elements

    # Crear arrglo de ids para guardar las categorias
    def save_categoris
        # category_elements ([1,2,3])
        return has_categories.destroy_all if category_elements.nil? || category_elements.empty?

        has_categories.where.not(category_id: category_elements).destroy_all

        categories_array.each do |category_id|
            # por cada elemento crea un registro en la tabla asociativa (HasCategory)
            # self es como this
            # validar si existe el registro. find_or_create_by si existe lo retorna y si no lo crea
            HasCategory.find_or_create_by(article: self, category_id: category_id)
        end
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :has_categories
    has_many :articles, through: :has_categories
end

app/models/has_category.rb
class HasCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article, only: [:show, :edit, :update, :destroy]

    def index
        @article = Article.all
        @categories = Category.all
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_param)
        @article.save_categoris
        @article.save

        render json: @article
    end

    def show
    end

    def edit
    end

    def update
        @article.update(article_param)
        @article.save_categoris
        redirect_to :action => :show, :id => @article.id
    end

    def destroy
        @article.destroy

        redirect_to root_path
    end

    private def article_param
        params.permit(:title, :content)
    end

    def find_article
        @article = Article.find(params[:id])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :color)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_for :post, :url => { :action => :create }, :class => "w-25" do %>
    <div class="mb-3">
        <%= label_tag :title, nil, :class => "form-label" %><br>
        <%= text_field_tag :title, nil, :class => "form-control" %>
    </div>

    <%
=begin%>
 <div class="mb-3">
        <%= label_tag :category_elements, nil, :class => "form-label" %><br>
        <div class="row">
            <%= @categories.each do |category| %>
                <label class="col-6 cols-sm-4">
                    <%= check_box_tag :category_elements, {multiple: true}, category.id, nil %>
                    <%= category.title %>
                </label>
            <% end %>
        </div>
    </div> 
<%
=end%>

    <div class="mb-3">
        <%= label_tag :content, nil, :class => "form-label" %><br>
        <%= text_area_tag :content, nil, :class => "form-control" %>
    </div>

    <p>
        <%= submit_tag :Enviar %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<%= form_for :post, :url => { :action => :update, :id => @article.id }, :method => :put, :class => "w-25" do %>
    <div class="mb-3">
        <%= label_tag :title, nil, :class => "form-label" %><br>
        <%= text_field_tag :title, nil, :class => "form-control" %>
    </div>

    <%
=begin%>
 <div class="mb-3">
        <%= label_tag :category_elements, nil, :class => "form-label" %><br>
        <div class="row">
            <%= @categories.each do |category| %>
                <label class="col-6 cols-sm-3">
                    <%= check_box_tag :category_elements, {multiple: true}, category.id, nil %>
                    <%= category.title %>
                </label>
            <% end %>
        </div>
    </div> 
<%
=end%>

    <div class="mb-3">
        <%= label_tag :content, nil, :class => "form-label" %><br>
        <%= text_area_tag :content, nil, :class => "form-control" %>
    </div>

    <p>
        <%= submit_tag :Enviar %>
    </p>
<% end %>

app/views/articles/index.html.erb
<h1>Mis artículos</h1>

<% @article.each do |art| %>
    <div class="card" style="padding: 15px; max-width: 300px; margin-top: 1em;">
        <h3 class="text-uppercase"><%= art.title %></h3>
        <p class="text-secondary"><%= art.created_at %></p>
        <%= link_to "Ver más", options = {:action => :show, :id => art.id} %>
    </div>
<% end %>

app/views/articles/new.html.erb
<%= render "articles/form" %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<div>
    <%= @article.content %>
</div>

<div>
    <p>Tags<p>
    <p>
        <% @article.categories.each do |category| %>
            <span class="badge" style="background-color: <%= category.color %>">
                <%= link_to category.title, category, class:'text-white' %>
            <span>
        <% end %>
    </p>
</div>

<div>
    <%= link_to "Editar", options = {:action => :edit, :id => @article.id}, html_options = { :class => 'btn btn-primary'} %>
    <%= link_to "Eliminar el articulo", options = {:action => :destroy, :id => @article.id}, html_options = {:method => :delete, :data => { :confirm => '¿Estas seguro?' }, :class => 'btn btn-danger'} %>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Title:</strong>
    <%= category.title %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= category.color %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.color_field :color %>
  </div>

  <div>
    <%= form.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Hola Mundo :)</h1>

<%= link_to "Inicio", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="nav bg-light">
    <li class="nav-item">
        <%= link_to "Inicio", root_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "Articulos", articles_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "Escribir", articles_new_path, class:"nav-link" %>
    </li>
</nav>